---
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/RequireMFA:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 12
